### ISSUE TITLE
GoogleMaps-override

### ISSUE THREAD

**Issue by ramsestom** [codenameone/codenameone-google-maps#27]
Could you provide the content of the GoogleMaps-override folder or tell how you made it? Because I forked the codenameone-google-maps project and tried to edit it to perform some change in the code but I have import issues (because the GoogleMaps-override folder do not exist in the github repository)

**Comment by shannah** [comment]
That directory isn't necessary.  You can either create an empty directory at the place that it wants it, or just remove it from the library dependencies.

**Comment by ramsestom** [comment]
It is necessary as google-play-services needs to be 9.4 at least. If you don't override the google-play-services provided by default by CN1 you have import issues ( like for `import com.google.android.gms.maps.OnMapReadyCallback;`)

**Comment by shannah** [comment]
Well, still, to answer your original question, I don't use the override directory.  My local dev copy doesn't even have one:

![image](https://user-images.githubusercontent.com/2677562/41308523-f7666914-6e30-11e8-9f76-fccc96efc2e3.png)

I just ignore that warning.

**Comment by ramsestom** [comment]
well how do you declare the google-play-service 9.4 dependency into you netbean project then (I hardly never use netbeans, I prefer eclipse but as CN1 eclipse plugin do not provide support for CN1 libs I am "forced" to use it for CN1 libs projects)? Because my compile-time libraries configuration is the same as yours but I have import errors in the editor (dur to googlemaps method that do no exist befor play-services 9.4)

**Comment by shannah** [comment]
I don't.  The dependency is added by the server.
The codenameone_library_required.properties file includes the following build hint to tell the server the required version of play services.

`codename1.arg.android.GoogleMaps.minPlayServicesVersion=9.4.0`

**Comment by ramsestom** [comment]
I am speaking of dependency at the netbean editor level. 
To avoid this kind of error in the editor:
![cn1maps_import_error](https://user-images.githubusercontent.com/636758/41310256-49c3b87e-6e81-11e8-9026-62cae09c8ae4.png)

**Comment by shannah** [comment]
I get the same errors in the editor.  When implementing native interfaces this just comes along with the territory.  When I'm working in Android, generally I do a build, include sources, then open up the project in Android studio and make changes there.

**Comment by ramsestom** [comment]
OK. That is not really convenient. I thought there was some way to tell netbeans to import google-play-services from a specific jar (I assumed GoggleMaps-override was used for that) rather than taking it from CodenameOne.jar by default to avoid this kind of errors. 
I tried to find a jar for google-play-services v9.4.0 to add it as a dependency to the netbean project but couldn't find ny in my android SDK folder (looks like google stopped distributing google-play-services as jars after froyo)
I will go with the Android studio solution for now even if it is not really convenient...

**Comment by shannah** [comment]
You can do that.  You would need to download the appropriate jar(s) from Google.  I think the last time I did something like this, I just scoured my local maven repos for the jars that I needed after building a project with my dependencies in Android studio.  Then just added the jars to my compile-time dependencies in Netbeans.

Generally it's not worth the hassle, as, like I said, you need to do that actually dev in Android studio so that you can test it on a device or in the Android emulator.

**Comment by codenameone** [comment]
Generally you shouldn't do that. The trick is pretty simple, you send a build of a test app with `include source` then download the source and open it in Android Studio. Then develop the native code there as it's more convenient. When done you just copy and paste the native code back into your IDE. We do the same thing for iOS and xcode otherwise it would be unbearable to write complex Objective-C code.

You can work with Eclipse and the cn1lib just fine... It's an Ant project you can open it and build it just like you can in NetBeans. The one thing missing from Eclipse is the option to create a new cn1lib project which is a bit of a pain to add.
