### ISSUE TITLE
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted.

### ISSUE THREAD

**Issue by mykovolod** [codenameone/codenameone-google-maps#38]
Looks like this extension is using BrowserComponent that has old UIWebView. It is not possible to load iOS build into Itunes connect because apple rejects build while this extension is included with the following error:
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability.
This error is gone when google-map extensions is not in the project so issue is here for sure

**Comment by jsfan3** [comment]
Hi Vlad Mykol,
`BrowserComponent` is used only inside `MapContainer.java`, that is not used on iOS... so I don't know why you have this issue.
More, `UIWebView` is not more the default since the summer 2019, as you can read here:
https://www.codenameone.com/blog/wkwebview-prs.html

By the way, try to add the following build hint to your project:
`ios.useWKWebView=true`
and add the following line in your `init()`:
`Display.getInstace().setProperty("BrowserComponent.useWKWebView", "true");`

This should solve. More info:
https://www.codenameone.com/blog/wkwebview.html

**Comment by mykovolod** [comment]
Thank you Francesco,
I tried all this already, but it did not help.
I don't know how but Apple detects UIWebView only when I have this library in the project, is it possible to detect it there somehow?

**Comment by jsfan3** [comment]
I'm sorry, I don't know. I tried to look at the source code of this cn1lib, but I didn't see anything problematic.

I saw your question also on Stack Overflow (https://stackoverflow.com/questions/62934174/itms-90809-deprecated-api-from-appstoreconnect-when-using-codenameone-google-ma), surely Shai Almog will reply you.

**Comment by mykovolod** [comment]
Looks like the issue was in another library with I missed in first place https://github.com/littlemonkeyltd/QRScanner
Sorry for the misinformation, closing as not a bug
